version: '3.8'
networks:

  localnet:
    name: localnet
    driver: bridge

volumes:
   lavareproject:
   nginx_data:

services:
  
  php-composer:
    build: .
    container_name: php-composer
    #restart: unless-stopped
    volumes:
      - type: volume
        source: lavareproject
        target: /var/www
      - nginx_data:/var/www/nginx-config
    depends_on:
      - mysql
    networks:
      - localnet
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: user
      DB_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: superPass
    command: ["/bin/bash", "-c", "/var/www/settings-laravel.sh"]


  nginx:
    image: nginx:1.25.4
    container_name: nginx-boilerplate
    # restart: unless-stopped
    ports:
      - '8080:80'
    networks:
      - localnet
    depends_on:
      - php-composer
    volumes:
      - nginx_data:/etc/nginx/conf.d
      - type: volume
        source: lavareproject
        target: /var/www

  mysql:
    image: mysql:oraclelinux8
    container_name: mysql
    #restart: unless-stopped
    networks:
      - localnet
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: superPass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: lavareproject
        target: /var/www
      
  node-yarn:
    image: node:20.10.0
    #restart: unless-stopped
    container_name: node-yarn
    networks:
      - localnet
    depends_on:
      - php-composer
    command: ["/bin/bash", "-c", "/var/www/settings-for-node-yarn.sh"]
    volumes:
      - type: volume
        source: lavareproject
        target: /var/www
    

