name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      with:
        # Тут ми додаємо опцію для викачування сабмодулів
        submodules: 'recursive'
      
    - name: Calculate unique tag
      id: prep
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to Registry php-composer
      uses: docker/login-action@v1
      with:
        registry: registry.local:5000
        username: ${{ secrets.DOCKER_USERNAME_LOCAL }}
        password: ${{ secrets.DOCKER_PASSWORD_LOCAL }}
        

    - name: Build the php-composer
      run: 
        docker build -t registry.local:5000/php-composer:${{ env.UNIQUE_TAG }} .
    
    - name: Push the php-composer
      run: 
        docker push registry.local:5000/php-composer:${{ env.UNIQUE_TAG }}