name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      with:
        # Тут ми додаємо опцію для викачування сабмодулів
        submodules: 'recursive'
      
    - name: Calculate unique tag
      id: prep
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to Registry PHP-one
      uses: docker/login-action@v1
      with:
        registry: registry.local:5000
        username: ${{ secrets.DOCKER_USERNAME_LOCAL }}
        password: ${{ secrets.DOCKER_PASSWORD_LOCAL }}
        
    - name: Log in to Registry Node-t
      uses: docker/login-action@v1
      with:
         registry: registry.local:5100
         username: ${{ secrets.DOCKER_USERNAME_LOCAL }}
         password: ${{ secrets.DOCKER_PASSWORD_LOCAL }}

    - name: Build the laravel-dock-php-one
      run: 
        docker build -t registry.local:5000/laravel-dock-php-one:${{ env.UNIQUE_TAG }} .
    
    - name: Push the laravel-dock-php-one
      run: 
        docker push registry.local:5000/laravel-dock-php-one:${{ env.UNIQUE_TAG }}

    - name: Build the laravel-dock-node-t
      run: 
        docker build -t registry.local:5100/laravel-dock-node-t:${{ env.UNIQUE_TAG }} .
    
    - name: Push the laravel-dock-node-t
      run: 
        docker push registry.local:5100/laravel-dock-node-t:${{ env.UNIQUE_TAG }}